---
title: "Machine Learning Aplicado"
subtitle: "Fluxo de trabalho comum em um projeto de ciência de dados"
author: "Fellipe Gomes - Blog: <a href='gomesfellipe.github.io'>gomesfellipe.github.io</a>"
date: "`r Sys.Date()`"
output:
  rmdformats::readthedown:
    highlight: kate
    toc_depth: 3
    number_sections: true
---

<a href="https://github.com/gomesfellipe" class="github-corner" aria-label="View source on GitHub"><svg width="80" height="80" viewBox="0 0 250 250" style="fill:#151513; color:#fff; position: absolute; top: 0; border: 0; right: 0;" aria-hidden="true"><path d="M0,0 L115,115 L130,115 L142,142 L250,250 L250,0 Z"></path><path d="M128.3,109.0 C113.8,99.7 119.0,89.6 119.0,89.6 C122.0,82.7 120.5,78.6 120.5,78.6 C119.2,72.0 123.4,76.3 123.4,76.3 C127.3,80.9 125.5,87.3 125.5,87.3 C122.9,97.6 130.6,101.9 134.4,103.2" fill="currentColor" style="transform-origin: 130px 106px;" class="octo-arm"></path><path d="M115.0,115.0 C114.9,115.1 118.7,116.5 119.8,115.4 L133.7,101.6 C136.9,99.2 139.9,98.4 142.2,98.6 C133.8,88.0 127.5,74.4 143.8,58.0 C148.5,53.4 154.0,51.2 159.7,51.0 C160.3,49.4 163.2,43.6 171.4,40.1 C171.4,40.1 176.1,42.5 178.8,56.2 C183.1,58.6 187.2,61.8 190.9,65.4 C194.5,69.0 197.7,73.2 200.1,77.6 C213.8,80.2 216.3,84.9 216.3,84.9 C212.7,93.1 206.9,96.0 205.4,96.6 C205.1,102.4 203.0,107.8 198.3,112.5 C181.9,128.9 168.3,122.5 157.7,114.1 C157.9,116.9 156.7,120.9 152.7,124.9 L141.0,136.5 C139.8,137.7 141.6,141.9 141.8,141.8 Z" fill="currentColor" class="octo-body"></path></svg></a><style>.github-corner:hover .octo-arm{animation:octocat-wave 560ms ease-in-out}@keyframes octocat-wave{0%,100%{transform:rotate(0)}20%,60%{transform:rotate(-25deg)}40%,80%{transform:rotate(10deg)}}@media (max-width:500px){.github-corner:hover .octo-arm{animation:none}.github-corner .octo-arm{animation:octocat-wave 560ms ease-in-out}}</style>

```{r setup, echo=FALSE, cache=FALSE}
library(knitr)
library(rmdformats)

## Global options
options(max.print="75")
opts_chunk$set(echo=FALSE,
	             cache=TRUE,
               prompt=FALSE,
               tidy=TRUE,
               comment=NA,
               message=FALSE,
               warning=FALSE)
opts_knit$set(width=75)
```

# Definição do Problema

## Descrição do problema

  * Descrição informal
  * Descrição formal
  * Premissas
  
## Dados Fornecidos

  * Restrições impostas aos dados
  * Definição de cada atributo
  
## Motivação

  * Motivação
  * Benefícios
  * Uso

# Resumir/Analisar Dados

## Estatísticas descritivas:

  * Estrutura dos dados
  * Distribui coes dos dados
  * Summary, VarType, Corr Matrix, Count os class labels

## Visualizações 

### Univariada

Avaliar cada atributo separadamente 

ex: tabela de frequência, gráfico de barras, Pareto, linha, histogramas, densidades, boxplots

### Bivariada

Avaliar atributos em relação à variável resposta (target)

ex: tabela de contingencia, boxplots, dispersão

### Multivariada

Como os atributos são correlacionados entre si

ex: Matrix de correlação

# Preparar dados

## Seleção de Atributos

Teste Qui-Quadrado
Coeficientes de Correlação
Algoritmos de eliminação recursiva (RFE)
Algoritmos de Regularização (LASSO, Elastic Net, Ridge Regression)

## Limpeza dos dados

Formato, Limpeza, Amostragem

## Testar suposições

Normalidade, igualdades, etc

## Transformação dos dados

Scale, decomposição, agregação

# Avaliar algoritmos

## Separar dados de treino/validação/teste

Treino/Teste
Cross-Validation

## Testar opções e métricas de avaliação

Por nível de dificuldade (do mais fácil para o mais difícil):

  1. knn, naive-bayes;
  2. logit, decision tree, lasso, elasticnet;
  3. randomforest, gbm, xgboost, nnet;
  4. h2o::automl, autoxgboost, autokeras;

## Algoritmos de verificação 

Conferir resultados com modelo baseline

## Comparar algoritmos

definir métricas, tempo de processamento, tempo de estimação etc

# Melhorar a acurácia

## Tuning algoritmos

Random Search
grid Search

## Conjuntos (Ensembles)

modelo hibrido

bagging, boosting, blending

"extreme feature engineering"

# Finalizar modelo

Contexto
Problema
Solução
Achados
Limita coes
Conclusões

## Previsões no dataset de teste

Automação?

## Salvar modelo para deploy / Operacionalizar algoritmo

API?
Shiny?
Script?
.RDS?