---
title: "Untitled"
author: "Fellipe"
date: "12 de março de 2018"
output: html_document
runtime: shiny
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = F,warning = F)
library(readxl)
library(ggplot2)
library(DT)


```
`

Este é um arquivo ... 

## Inputs para seu relatorio

Você pode incluir o output que desejar e o relatório pode ser todo programado para que sempre que um novo conjunto de dados seja incluido seus resultados sejam atualizados.

```{r eruptions, echo=FALSE}
inputPanel(
    textInput("Airpassenger", label = h3("Qual a planilha?"),  # Input: Insere strings que considerados stopwords
                  value = "AirPassenger"),
  selectInput(inputId = "formato",                                            # Seleciona o formato do arquivo
                    label = "Selecione o formato do arquivo:",
                    choices = c("csv/txt", "excel")),
fileInput("file1", "Escolha o arquivo no formato CSV",                      # Input: Selecionar um arquivo csv do computador 
                  multiple = TRUE,                                                  # Permite carregar mais de um arquivo
                  accept = c("text/csv",                                            # Tipos de arquivos aceitos
                             "text/comma-separated-values,text/plain",
                             ".csv"))
)


df <- reactive({   if(input$formato=="excel"){                  # Leitura dos dados ficara armazenada no objeto terms
    req(input$file1)                                                 # Para limpar mensagem de erro antes de carregar a base
    df <- read_excel(input$file1$datapath,sheet = input$plan)        # Leitura de base excel
    
  }else{                                                             # Se o arquivo nao for excel
    
    req(input$file1)                                                 # Leitura dos dados ficara armazenada no objeto terms
    df = read.csv(input$file1$datapath,                              # Leitura da base de dados com os inputs obtidos em ui
                  header = T,                                        # Base precisa ter cabeçalho
                  sep = input$sep,encoding = "UTF-8")                # separação informada pelo usuario
  }})


```

## Plot da tabela

Assim que o arquivo for inserido, abaixo será apresentda a tabela com os dados:

```{r tabsets, echo=FALSE}
renderDataTable({
  df=df()
    df%>%
      ts(frequency = 12)%>%
      datatable()
})
```

Note que existem varias opções ...

## Plot da série

```{r}
renderPlot({
  df=df()
  
  
  df%>%
    ts(frequency = 12)%>%
    decompose()%>%
    plot()
})
```



